spring:
  application.name: subte
  jpa:
    hibernate.ddl-auto: validate
    properties.hibernate:
      default_schema: subte_bot
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      temp.use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://football-db:5432/football-db
    username:
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration/common
    baseline-on-migrate: true
    ignore-missing-migrations: false
    out-of-order: false
    schemas: subte_bot
